name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-26]
        build_type: [cpu, cuda, metal]
        exclude:
          - os: macos-26
            build_type: cpu
          - os: macos-26
            build_type: cuda
          - os: ubuntu-latest
            build_type: metal
          - os: ubuntu-24.04-arm
            build_type: metal
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Set up devcontainer (Linux only)
        if: runner.os == 'Linux'
        uses: ./.github/workflows/actions/devcontainer
        id: devcontainer
      - name: setup exec
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            echo 'EXEC=${{ steps.devcontainer.outputs.exec }}' >> $GITHUB_ENV
          else
            echo 'EXEC=' >> $GITHUB_ENV
          fi
      - name: Cache Homebrew downloads
        if: runner.os == 'macOS'
        uses: actions/cache@v5
        with:
          path: ~/Library/Caches/Homebrew/downloads
          key: brew-ccache-${{ runner.os }}
      - name: Install ccache (macOS only)
        if: runner.os == 'macOS'
        run: brew install ccache
      - name: Get submodule commit
        id: submodule
        run: echo "sha=$(git rev-parse HEAD:llama.cpp)" >> $GITHUB_OUTPUT
      - name: Cache ccache
        uses: actions/cache@v5
        with:
          path: .ccache
          key: ccache-${{ matrix.os }}-${{ matrix.build_type }}-${{ steps.submodule.outputs.sha }}
          restore-keys: |
            ccache-${{ matrix.os }}-${{ matrix.build_type }}-
      - name: Cache Models
        uses: actions/cache@v5
        with:
          path: .cache
          key: models-${{ matrix.os }}-${{ hashFiles('Makefile') }}
      - name: Build ${{ matrix.build_type }}
        env:
          CCACHE_MAXSIZE: 512M
        run: |
            if [ "${{ matrix.build_type }}" = "cuda" ]; then
              ${{ env.EXEC }} sudo sh -ceux 'cd /usr/local/cuda/lib64/stubs/;rm -f libcuda.so.1;ln -s libcuda.so libcuda.so.1'
            fi
            ${{ env.EXEC }} sh -ceux "mkdir -p .ccache .cache && LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs CCACHE_DIR=\$(pwd)/.ccache CCACHE_MAXSIZE=$CCACHE_MAXSIZE make ${{ matrix.build_type }}.build"
            ${{ env.EXEC }} sh -ceux "CCACHE_DIR=\$(pwd)/.ccache ccache -s"
      - name: Run ${{ matrix.build_type }}
        if: matrix.build_type != 'cuda'
        run: |
            ${{ env.EXEC }} sh -ceux "LLAMA_CACHE=\$(pwd)/.cache make ${{ matrix.build_type }}.run"
      - name: Bench ${{ matrix.build_type }}
        if: matrix.build_type != 'cuda'
        run: |
            ${{ env.EXEC }} sh -ceux "LLAMA_CACHE=\$(pwd)/.cache make ${{ matrix.build_type }}.bench BENCH_TYPE=--fast"
