name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14]
        build_type: [cpu, cuda, metal]
        exclude:
          - os: macos-14
            build_type: cpu
          - os: macos-14
            build_type: cuda
          - os: ubuntu-latest
            build_type: metal
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up devcontainer (Linux only)
        if: matrix.os == 'ubuntu-latest'
        uses: ./.github/workflows/actions/devcontainer
        id: devcontainer
      - name: setup exec
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            echo 'EXEC=${{ steps.devcontainer.outputs.exec }}' >> $GITHUB_ENV
          else
            echo 'EXEC=' >> $GITHUB_ENV
          fi
      - name: Install ccache (macOS only)
        if: matrix.os != 'ubuntu-latest'
        run: brew install ccache
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ccache-${{ matrix.os }}-${{ matrix.build_type }}-${{ hashFiles('.gitmodules') }}
          restore-keys: |
            ccache-${{ matrix.os }}-${{ matrix.build_type }}-
      - name: Cache Models
        uses: actions/cache@v4
        with:
          path: .cache
          key: models-${{ matrix.os }}-${{ hashFiles('Makefile') }}
      - name: Build ${{ matrix.build_type }}
        env:
          CCACHE_MAXSIZE: 512M
        run: |
            if [ "${{ matrix.build_type }}" = "cuda" ]; then
              ${{ env.EXEC }} sudo sh -ceux 'cd /usr/local/cuda/lib64/stubs/;rm -f libcuda.so.1;ln -s libcuda.so libcuda.so.1'
              ${{ env.EXEC }} sh -ceux "mkdir -p .ccache .cache && LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs CCACHE_DIR=\$(pwd)/.ccache CCACHE_MAXSIZE=$CCACHE_MAXSIZE LLAMA_CACHE=\$(pwd)/.cache make ${{ matrix.build_type }}"
            else
              ${{ env.EXEC }} sh -ceux "mkdir -p .ccache .cache && CCACHE_DIR=\$(pwd)/.ccache CCACHE_MAXSIZE=$CCACHE_MAXSIZE LLAMA_CACHE=\$(pwd)/.cache make ${{ matrix.build_type }}"
            fi
